tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
  - name: flyio
    command: |
      curl -L https://fly.io/install.sh | sh
      /home/gitpod/.fly/bin/flyctl auth login
  - name: tailscale
    command: |
      cd /tmp
      wget https://pkgs.tailscale.com/stable/tailscale_1.44.0_amd64.tgz
      tar zxvf tailscale_1.44.0_amd64.tgz
      sudo mv tailscale_*/tailscale{,d} /usr/sbin/
      sudo tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 41641 2>/dev/null &
      sudo tailscale up --authkey=${TAILSCALE_AUTHKEY} --operator=gitpod --netfilter-mode=off --ssh

ports:
  - port: 5000
    onOpen: ignore
  - port: 5601
    onOpen: open-browser
  - port: 9200
    onOpen: open-preview
  - port: 9300
    onOpen: ignore
  - port: 9600
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - tailscale.vscode-tailscale
