version: '3.3'
services:
    linuxserver:
        container_name: code-server
        image: 'lscr.io/linuxserver/code-server:latest'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - PASSWORD=password
            - HASHED_PASSWORD=
            - SUDO_PASSWORD=password
            - SUDO_PASSWORD_HASH=
            - PROXY_DOMAIN=code-server.my.domain
            - DEFAULT_WORKSPACE=/config/workspace
        ports:
            - '8443:8443'
        volumes:
            - '/path/to/appdata/config:/config'
        restart: unless-stopped
